/**
 * Account API — generate, import, restore, validate, EVM bind.
 * Ports keyring.ts and accountApi.ts from reef-mobile-js.
 */

import {Keyring} from '@polkadot/keyring';
import {
  mnemonicGenerate,
  mnemonicValidate,
  cryptoWaitReady,
  isAddress,
  isEthereumAddress,
} from '@polkadot/util-crypto';
import {u8aToHex, isHex} from '@polkadot/util';
import type {KeyringPair, KeyringPair$Json} from '@polkadot/keyring/types';
import {SS58_FORMAT, KEYPAIR_TYPE} from './config';
import {getProvider, getApi} from './networkApi';
import {reefSigner} from './signer';

let keyring: Keyring | null = null;
let wasmReady = false;

/** Initialize WASM crypto and keyring */
export async function initKeyring(): Promise<void> {
  if (!wasmReady) {
    await cryptoWaitReady();
    wasmReady = true;
  }
  if (!keyring) {
    keyring = new Keyring({type: KEYPAIR_TYPE, ss58Format: SS58_FORMAT});
  }
}

function getKeyring(): Keyring {
  if (!keyring) {
    throw new Error('Keyring not initialized. Call initKeyring() first.');
  }
  return keyring;
}

// --- Account Generation ---

export interface GeneratedAccount {
  mnemonic: string;
  address: string;
  svg: string;
}

/**
 * Generate a new account with a random mnemonic.
 */
export async function generateAccount(): Promise<GeneratedAccount> {
  await initKeyring();
  const mnemonic = mnemonicGenerate(12);
  const pair = getKeyring().addFromMnemonic(mnemonic);

  return {
    mnemonic,
    address: pair.address,
    svg: '', // Identicon SVG will be generated by the UI component
  };
}

/**
 * Derive account from an existing mnemonic.
 */
export async function accountFromMnemonic(
  mnemonic: string,
): Promise<GeneratedAccount | null> {
  await initKeyring();
  if (!mnemonicValidate(mnemonic)) {
    return null;
  }
  const pair = getKeyring().addFromMnemonic(mnemonic);

  return {
    mnemonic,
    address: pair.address,
    svg: '',
  };
}

/**
 * Validate a mnemonic seed phrase.
 */
export function checkMnemonicValid(mnemonic: string): boolean {
  return mnemonicValidate(mnemonic);
}

/**
 * Get a KeyringPair from a mnemonic.
 */
export async function keyPairFromMnemonic(
  mnemonic: string,
): Promise<KeyringPair | null> {
  await initKeyring();
  if (!mnemonicValidate(mnemonic)) {
    return null;
  }
  return getKeyring().addFromMnemonic(mnemonic);
}

// --- JSON Import/Export ---

/**
 * Restore account from encrypted JSON backup.
 */
export async function restoreFromJson(
  json: KeyringPair$Json,
  password: string,
): Promise<{address: string; name: string} | null> {
  await initKeyring();
  try {
    const pair = getKeyring().addFromJson(json);
    pair.decodePkcs8(password);
    return {
      address: pair.address,
      name: (json.meta?.name as string) ?? '',
    };
  } catch {
    return null; // Invalid password or corrupt JSON
  }
}

/**
 * Export account as encrypted JSON.
 */
export function exportAccountJson(
  address: string,
  password: string,
): KeyringPair$Json | null {
  try {
    const pair = getKeyring().getPair(address);
    return pair.toJson(password);
  } catch {
    return null;
  }
}

// --- Address Validation ---

/**
 * Check if a string is a valid Substrate (SS58) address.
 */
export function isValidSubstrateAddress(address: string): boolean {
  return isAddress(address);
}

/**
 * Check if a string is a valid EVM address.
 */
export function isValidEvmAddress(address: string): boolean {
  return isEthereumAddress(address);
}

// --- EVM Binding ---

/**
 * Claim EVM account for a native address.
 * This binds the EVM address to the Substrate account.
 */
export async function claimEvmAccount(
  nativeAddress: string,
): Promise<boolean> {
  const api = getApi();
  if (!api) throw new Error('API not connected');

  try {
    const tx = api.tx.evmAccounts.claimDefaultAccount();

    await new Promise<void>((resolve, reject) => {
      tx.signAndSend(
        nativeAddress,
        {signer: reefSigner},
        ({status, dispatchError}) => {
          if (dispatchError) {
            reject(new Error(dispatchError.toString()));
          } else if (status.isFinalized) {
            resolve();
          }
        },
      );
    });

    return true;
  } catch {
    return false;
  }
}

/**
 * Resolve EVM address from native address.
 */
export async function resolveEvmAddress(
  nativeAddress: string,
): Promise<string | null> {
  const api = getApi();
  if (!api) return null;

  try {
    const evmAddress = await api.query.evmAccounts.evmAddresses(nativeAddress);
    const hex = evmAddress.toString();
    return hex === '0x' + '0'.repeat(40) ? null : hex;
  } catch {
    return null;
  }
}

/**
 * Resolve native address from EVM address.
 */
export async function resolveFromEvmAddress(
  evmAddress: string,
): Promise<string | null> {
  const api = getApi();
  if (!api) return null;

  try {
    const accounts = await api.query.evmAccounts.accounts(evmAddress);
    const addr = accounts.toString();
    return addr || null;
  } catch {
    return null;
  }
}

/**
 * Sign a payload using the account's mnemonic directly.
 * Used for signing operations that bypass the UI (e.g., internal ops).
 */
export async function signWithMnemonic(
  mnemonic: string,
  message: Uint8Array,
): Promise<Uint8Array> {
  await initKeyring();
  const pair = getKeyring().addFromMnemonic(mnemonic);
  return pair.sign(message);
}
