# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReefNative' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Suppress third-party pod warnings treated as errors
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        case target.name
        when 'react-native-webview'
          build_config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-shorten-64-to-32'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-nonnull'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
        when 'react-native-camera-kit'
          build_config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-incompatible-pointer-types'
        when 'RNCClipboard'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-mismatched-parameter-types'
        when 'RNGestureHandler'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-unused-function'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-documentation'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-implicit-retain-self'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-objc-missing-super-calls'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-enum-conversion'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-return-type'
        when 'RNKeychain'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-comma'
        when 'RNScreens'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-switch'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-format'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-documentation'
        when 'RNSVG'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-objc-missing-super-calls'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-vla-extension'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-unused-function'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-static-inline-explicit-instantiation'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-auto-var-id'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-objc-property-synthesis'
        when 'RNWorklets'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-shorten-64-to-32'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-unused-function'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-documentation'
        when 'RNReanimated'
          build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-shorten-64-to-32'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-nullability-completeness'
        when 'React-Fabric'
          build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
          build_config.build_settings['OTHER_CFLAGS'] << '-Wno-documentation'
        end
      end
    end
  end
end
